# Generated by Django 5.1.1 on 2024-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('detalles', models.TextField(max_length=500)),
            ],
        ),
    ]
