# Generated by Django 5.1.1 on 2025-06-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('prestador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestador.prestador'),
        ),
    ]
