# Generated by Django 5.1.1 on 2024-10-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('servicio', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateTimeField()),
                ('fecha_servicio', models.DateTimeField()),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], max_length=20)),
                ('detalles', models.TextField(max_length=1000)),
                ('direccion_consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.direccionconsumidor')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
                ('servicio_prestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicioprestado')),
            ],
        ),
    ]
