# Generated by Django 5.1.1 on 2025-06-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateTimeField()),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aceptada'), (3, 'Rechazada')], default=1)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contrato', models.DateTimeField()),
                ('fecha_servicio', models.DateTimeField()),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado', models.IntegerField(choices=[(1, 'En proceso'), (2, 'Cancelado'), (3, 'Completado')])),
                ('detalles', models.TextField(blank=True, max_length=1000, null=True)),
                ('consumidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='consumidor.consumidor')),
            ],
        ),
    ]
