# Generated by Django 5.1.1 on 2024-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_remove_contrato_direccion_consumidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[(1, 'En proceso'), (2, 'Cancelado'), (3, 'Completado')], max_length=20),
        ),
    ]
