# Generated by Django 5.1.1 on 2024-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_alter_contrato_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='detalles',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Cancelado'), (3, 'Completado')]),
        ),
    ]
