# Generated by Django 5.1.1 on 2024-10-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('ubicacion', '0002_alter_direccion_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioprestado',
            name='barrio',
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='localidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.localidad'),
        ),
    ]
