# Generated by Django 5.1.7 on 2025-06-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioprestado',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
