# Generated by Django 5.1.1 on 2024-11-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_remove_servicioprestado_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
