# Generated by Django 5.1.1 on 2025-06-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioprestado',
            name='servicio',
        ),
    ]
