# Generated by Django 5.1.7 on 2025-06-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_servicioprestado_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioprestado',
            name='servicio',
        ),
        migrations.AddField(
            model_name='servicioprestado',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio.categoria'),
            preserve_default=False,
        ),
    ]
