# Generated by Django 5.1.1 on 2025-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudios', models.TextField(blank=True, max_length=500, null=True)),
                ('codFiscal', models.CharField(blank=True, max_length=100, null=True)),
                ('CUIT', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
