# Generated by Django 5.1.1 on 2024-11-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestador', '0002_alter_prestador_usuario'),
        ('usuario', '0003_alter_rol_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestador',
            name='CUIT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='rol_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='codFiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='estudios',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
