# Generated by Django 5.1.7 on 2025-06-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidor', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidor',
            name='rol_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
    ]
