# Generated by Django 5.1.1 on 2024-11-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumidor', '0001_initial'),
        ('usuario', '0003_alter_rol_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.rol'),
        ),
    ]
