# Generated by Django 5.1.1 on 2024-11-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumidor', '0002_alter_consumidor_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumidor',
            old_name='usuario',
            new_name='rol_usuario',
        ),
    ]
