# Generated by Django 5.1.1 on 2024-11-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_rol_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='usuario.usuario'),
        ),
    ]
