# Generated by Django 5.1.1 on 2024-11-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_rol_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='usuario_generico', max_length=150, unique=True),
        ),
    ]
