# Generated by Django 5.1.1 on 2024-11-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_options_alter_usuario_managers_and_more'),
        ('usuario', '0007_remove_usuario_usuario'),
    ]

    operations = [
    ]
