# Generated by Django 5.1.1 on 2024-10-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.TextField(max_length=200)),
                ('altura', models.TextField(max_length=200)),
                ('departamento', models.CharField(default='N/A', max_length=100, null=True)),
                ('codigo_postal', models.CharField(max_length=100)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='DireccionConsumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumidor.consumidor')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='barrio',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.localidad'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.provincia'),
        ),
    ]
