# Generated by Django 5.1.1 on 2024-10-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_remove_contrato_direccion_consumidor_and_more'),
        ('servicio', '0002_remove_servicioprestado_barrio_and_more'),
        ('ubicacion', '0002_alter_direccion_departamento'),
        ('usuario', '0002_remove_usuario_rol_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='barrio',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='direccionconsumidor',
            name='consumidor',
        ),
        migrations.RemoveField(
            model_name='direccionconsumidor',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ubicacion.localidad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='DireccionConsumidor',
        ),
    ]
