# Generated by Django 5.1.1 on 2024-11-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
        ('prestador', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='Calificacion',
            new_name='calificacion',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='prestador.prestador'),
        ),
    ]
