# Generated by Django 5.1.1 on 2024-10-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='Calificacion',
            new_name='calificacion',
        ),
    ]
