# Generated by Django 5.1.1 on 2024-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Cancelado'), (3, 'Completado')], max_length=20),
        ),
    ]
