# Generated by Django 5.1.1 on 2024-11-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_alter_pago_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
