# Generated by Django 5.1.1 on 2024-11-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='detalle',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
