# Generated by Django 5.1.1 on 2024-11-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_alter_metodopago_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.IntegerField(choices=[(1, 'En proceso'), (2, 'Cancelado'), (3, 'Completado')]),
        ),
    ]
